### ISSUE TITLE
大佬您好，请问这套程序是否可以适用三位一体的联机改善？

### ISSUE THREAD

**Issue by plutoxxy** [ArkciaDragone/Relay9P#1]
谢谢大佬！

**Comment by ArkciaTheDragon** [comment]
1. 直接用大概是不行的
2. 没有测试过前 4 代，但 5 代似乎改了联机设计，也不使用这个服务器地址
3. 我猜想前 4 代原理上可以用类似的方法解决，但数据包的格式可能不同，需要抓一下才能知道；抓取的部分是直接改写的，我不太了解

不客气！
